function StringBuilder(){var b=[];this.append=function(c){null!=c&&b.push(c)};this.getValue=function(){return b.join("")}}function stringFormat(b,c){return b.replace(/{(\d+)}/g,function(b,a){return c[a]})};function BooleanVariable(b){var c=Boolean(b);this.set=function(b){c=Boolean(b)};this.get=function(){return c};this.size=function(){return 1};this.toInt16Array=function(){return c?[1]:[0]};this.fromInt16Array=function(b){c=1==(b[0]&1)}}
function IntegerVariable(b,c,n,a){function h(f){f=Math.floor(f);isNaN(f)&&(f=0);f<b&&(f=a?((f-d)%p+p)%p+b:d);f>c&&(f=a?(f-d)%p+b:m);return f}if(c<b)throw Error("max cannot be less than min");var d=b,m=c,p=c-b+1,f=Math.ceil(Math.log(p)/Math.log(2)),g=h(n);this.set=function(f){g=h(f)};this.get=function(){return g};this.size=function(){return f};this.toInt16Array=function(){for(var a=[],h=Math.ceil(f/16),b=g-d,c=0;c<h;c++)a[c]=b%65536,b=Math.floor(b/65536);return a};this.fromInt16Array=function(f){for(var a=
0,b=f.length-1;0<=b;b--)a*=65536,a+=f[b];g=h(a+d)}}
function NumberVariable(b){function c(a){if(a==Number.POSITIVE_INFINITY)return{sign:0,biasedExponent:2047,mantissa:0};if(a==Number.NEGATIVE_INFINITY)return{sign:1,biasedExponent:2047,mantissa:0};if(isNaN(a))return{sign:1,biasedExponent:2047,mantissa:0xfffffffffffff};if(0==a)return{sign:0,biasedExponent:0,mantissa:0};var h={};h.sign=0>a?1:0;a=Math.abs(a);var d=Math.floor(Math.log(a)/Math.log(2));h.biasedExponent=d+1023;0==h.biasedExponent?(d=Math.pow(2,-1022),h.mantissa=a/d*4503599627370496):(d=Math.pow(2,
d),h.mantissa=4503599627370496*(a/d-1));return h}var n=Number(b);this.set=function(a){n=Number(a)};this.get=function(){return n};this.size=function(){return 64};this.toInt16Array=function(){for(var a=c(n),h=a.mantissa,d=[],b=0;3>b;b++)d[b]=h%65536,h=Math.floor(h/65536);d[3]=a.sign<<15|a.biasedExponent<<4|h;return d};this.fromInt16Array=function(a){var b,d;d=a[3]&15;for(b=2;0<=b;b--)d*=65536,d+=a[b];b=d;d=a[3]>>4&2047;a=a[3]>>15;2047==d?n=0==b?0==a?Number.POSITIVE_INFINITY:Number.NEGATIVE_INFINITY:
NaN:(0==d?(b/=4503599627370496,d=Math.pow(2,-1022)):(b=1+b/4503599627370496,d=Math.pow(2,d-1023)),d*=b,n=1==a?-d:d)}};function Set(){function b(b){var f=a[b];if(f)return f;throw Error(stringFormat("Index not found '{0}'",[b]));}function c(a){if(0<=h[a])return h[a];throw Error(stringFormat("Name not found '{0}'",[a]));}function n(a,f){var g=b(a)[f];if(g)return g;throw Error(stringFormat("Key not found '{0}'",[f]));}for(var a=[],h={},d=0;d<arguments.length;d++){var m=arguments[d];a.push(m);if(!m.name)throw Error("Missing name in set");h[m.name]=d}this.getByIndex=b;this.size=function(){return a.length};this.get=function(a){return b(c(a))};
this.getName=function(a){return b(a).name};this.getAllNames=function(){for(var b=[],f=0;f<a.length;f++)b.push(a[f].name);return b};this.getIndex=c;this.getByIndex=b;this.lookup=function(a,f){return n(c(a),f)};this.lookupByIndex=n}
function Relation(){function b(){if(arguments.length!=h.length)throw Error(stringFormat("Wrong number of keys ({0}), expected ({1})",[arguments.length,h.length]));for(var a=0,b=0;b<h.length;b++)var d=h[b],a=a*d.size()+d.getIndex(arguments[b]);return a}function c(a){a=b.apply(this,a);var g=1<<a%16;return(d[a>>4]&g)==g}function n(a,b,d){for(var m=0;m<a.length&&null!=a[m];)m++;if(m==a.length)c(a)&&d.push(b.slice(0,b.length));else{for(var p=h[m],k=0;k<p.size();k++){var s=p.getName(k);a[m]=s;b.push(s);
n(a,b,d);b.pop()}a[m]=null}}for(var a=1,h=[],d=[],m=0;m<arguments.length;m++){var p=arguments[m],a=a*p.size();h.push(p)}for(m=0;m<a;m+=16)d.push(0);this.set=function(){var a=b.apply(this,arguments),g=a>>4;d[g]|=1<<a%16};this.clear=function(){var a=b.apply(this,arguments),g=a>>4;d[g]&=~(1<<a%16)};this.check=function(){return c(arguments)};this.find=function(){var a=[];n(arguments,[],a);return a};this.size=function(){return a};this.toInt16Array=function(){for(var a=[],b=0;b<d.length;b++)a.push(d[0]);
return a};this.fromInt16Array=function(a){for(var b=0;b<d.length;b++)d[b]=a[b]}};function RandomNumberGenerator(){var b=new IntegerVariable(0,Math.pow(2,32)-1,Math.floor(Math.random()*Math.pow(2,32)),!1),c=Math.pow(2,32),n=Math.pow(2,52);this.getByte=function(){var a=b.get(),a=(1664525*a+1013904223)%c;b.set(a);return(a&1044480)>>12};this.getDouble=function(){for(var a=0,b=0;6>b;b++)a*=256,a+=this.getByte();a=16*a+(this.getByte()>>4);return a/n};this.getBoolean=function(a){return this.getDouble()<a};this.getNumber=function(a,b){return this.getDouble()*(b-a)+a};this.getInteger=
function(a,b){return Math.floor(this.getNumber(a,b))};this.size=function(){return b.size()};this.toInt16Array=function(){return b.toInt16Array()};this.fromInt16Array=function(a){b.fromInt16Array(a)}}var random=new RandomNumberGenerator;var Base64=function(){for(var b={},c=0;64>c;c++)b["0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_".charAt(c)]=c;return{Builder:function(){var b="",a=0,c=0;this.addInt16Array=function(d,m){for(var p=0;p<d.length;p++){for(var f=Math.min(m,16),g=d[p],l=f,g=g<<c|a,l=l+c;6<=l;)b+="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_".charAt(g&63),l-=6,g>>=6;a=g;c=l;m-=f}};this.chars=function(){return 0==c?b:b+"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_".charAt(a)}},
Reader:function(c){function a(a){for(var c=m,l=p;l<a;)c|=b[h.charAt(d++)]<<l,l+=6;p=l-a;m=c>>a;return c&(1<<a)-1}var h=c,d=0,m=0,p=0;this.readInt16Array=function(b){for(var d=[];0<b;){var c=Math.min(b,16);d.push(a(c));b-=c}return d}}}}();function State(b,c){function n(b){b=new Base64.Reader(b);for(var c=0;c<a.length;c++){var h=a[c],f=b.readInt16Array(h.size());h.fromInt16Array(f)}}var a=b;this.toBase64=function(){for(var b=new Base64.Builder,c=0;c<a.length;c++){var h=a[c];b.addInt16Array(h.toInt16Array(),h.size())}return b.chars()};this.fromBase64=n;var h=window.location.hash.replace(/^#/,"");0==h.length?(h=this.toBase64(),window.location.hash=h):n(h);window.setInterval(function(){var a=window.location.hash.replace(/^#/,"");a!=h&&
(h=a,n(h),c())},100)};function Compiler(b,c){function n(){var a;this.get=function(){return a};this.set=function(b){a=b}}function a(){var a=[];this.addLine=function(b){a.push(b)};this.execute=function(){for(var b=new StringBuilder,c=0;c<a.length;c++){var d=a[c];try{b.append(d.execute())}catch(e){if(d.source)throw Error(stringFormat("Unable to execute statement '{0}':\n{1}",[d.source,e.message]));}}return b.getValue()}}function h(b){function c(b){e={condition:b,block:new a};d.push(e)}var d=[],e;c(b);this.addCondition=function(a){if(null==
e.condition)throw Error("Unreachable 'else' clause");c(a)};this.addLine=function(a){e.block.addLine(a)};this.execute=function(){for(var a=0;a<d.length;a++){var b=d[a];if(null==b.condition||b.condition.evaluate().value)return b.block.execute()}}}function d(a,b,c){c=c.evaluate();var d=new StringBuilder;if(c.hasNext&&c.next)for(;c.hasNext();)b.assign(c.next()),d.append(a.execute());else if(c instanceof Array)for(var e=0;e<c.length;e++)b.assign(c[e]),d.append(a.execute());else b.assign(value),d.append(a.execute());
return d.getValue()}function m(a){this.evaluate=function(){return a.evaluate().value};this.assign=a.assign.bind(a)}function p(b,c){for(var d=new a,e=[d],f=0;f<c.length;f++)e.push(new m(c[f]));this.addLine=function(a){d.addLine(a)};this.execute=function(){return b.apply(null,e)}}function f(a){throw Error("Expression cannot be assigned to");}function g(a){return{value:a,output:!0}}function l(a){return{value:a,output:!1}}function y(a){return{evaluate:function(){return g(a)},assign:function(a){throw Error("Attempt to assign to literal");
}}}function t(a){return{evaluate:function(){return g(a.get())},assign:function(b){a.set(b);return l(a.get())}}}function k(a,b,c){return c?{evaluate:function(){evaluatedParameters=b.evaluate().value;return g(a.apply(null,b.items?evaluatedParameters:[evaluatedParameters]).get())},assign:function(c){evaluatedParameters=b.evaluate().value;return l(a.apply(null,b.items?evaluatedParameters:[evaluatedParameters]).set(c))}}:{evaluate:function(){evaluatedParameters=b.evaluate().value;return g(a.apply(null,
b.items?evaluatedParameters:[evaluatedParameters]))},assign:f}}function s(a,b){return{block:new p(a,b.items?b.items:[b]),evaluate:function(){throw Error("Block functions cannot be evaluated in a statement.");},assign:f}}function D(a){return{items:a,evaluate:function(){for(var b=[],c=0;c<a.length;c++)b.push(a[c].evaluate().value);return l(b)},assign:function(b){if(b instanceof Array){for(var c=Math.min(a.length,b.length),d=[],e=0;e<c;e++)d.push(a[e].assign(b[e]));return l(d)}return 0<a.length?l(a[0].assign(b)):
l([])}}}function x(){var a=[];this.addToken=function(b){switch(b.tokenType){case e.operator:var c=a.pop(),d=a.pop();a.push(b.expression(d,c));break;case e.unaryOperator:c=a.pop();a.push(b.expression(c));break;case e.func:a.push(k(b.operation,a.pop(),b.propertyResult));break;case e.blockFunc:a.push(s(b.operation,a.pop()));break;case e.literal:a.push(y(b.value));break;case e.variable:a.push(t(b.value));break;case e.array:a.push(K);break;case e.leftBracket:a.push(L);break;case e.rightBracket:for(b=[];!(c=
a.pop()).bracketType;)b.push(c);1==b.length&&c.bracketType!=H.array?a.push(b[0]):a.push(D(b.reverse()))}};this.getExpression=function(){if(0==a.length)throw Error("Empty expression");if(1<a.length)throw Error("Incomplete expression");return a.pop()}}function E(){function a(b){if(0==c.length)return!1;for(var d=c[c.length-1].tokenType,e=0;e<b.length;e++)if(d==b[e])return!0;return!1}function b(a){if(0==c.length)return!1;var d=c[c.length-1];return d.tokenType==e.unaryOperator||d.tokenType==e.operator&&
d.precedence>=a}var c=[],d=new x;this.addToken=function(f){switch(f.tokenType){case e.array:c.push(f);break;case e.leftBracket:a([e.array])?d.addToken(c.pop()):d.addToken(f);c.push(f);break;case e.rightBracket:for(;!a([e.leftBracket]);)d.addToken(c.pop());c.pop();d.addToken(f);a([e.func,e.blockFunc])&&d.addToken(c.pop());break;case e.separator:for(;!a([e.leftBracket]);)d.addToken(c.pop());break;case e.operator:for(;b(f.precedence);)d.addToken(c.pop());c.push(f);break;case e.unaryOperator:c.push(f);
break;case e.func:case e.blockFunc:c.push(f);break;default:d.addToken(f)}};this.getExpression=function(){for(;0<c.length;)d.addToken(c.pop());return d.getExpression()}}function A(a){return{execute:function(){return a}}}function M(a,b){return{execute:function(){var b=a.evaluate();if(b.output)return b.value},source:b}}var F=/((\[\[)|([^[]))+|(\[(("(([\\]")|[^"])*")|([^\]]))*\])/g,I=/^\[(("((\\")|[^"])*")|([^\]]))*\]$/,N=/[^\$_a-zA-Z0-9\s"]|([0-9]*\.[0-9]+)|([0-9]+)|(\$[_a-zA-Z0-9]+)|([_a-zA-Z][_a-zA-Z0-9]*)|("((\\")|[^"])*")/g,
J=/^[_a-zA-Z][_a-zA-Z0-9]*$/,O=/^\$[_a-zA-Z0-9]+$/,P=/^([0-9]*\.[0-9])|([0-9]+)$/,Q=/^"((\\")|[^"])*"$/,e={leftBracket:1,rightBracket:2,separator:5,func:6,blockFunc:7,operator:8,unaryOperator:9,variable:10,literal:11,marker:12,array:13},r={incomplete:1,complete:2,func:3},u=[];u[e.leftBracket]=r.start;u[e.rightBracket]=r.complete;u[e.separator]=r.start;u[e.func]=r.func;u[e.operator]=r.incomplete;u[e.unaryOperator]=r.incomplete;u[e.variable]=r.complete;u[e.literal]=r.complete;u[e.array]=r.func;var B=
{tokenType:e.leftBracket},v={tokenType:e.rightBracket},q={tokenType:e.separator},w={tokenType:e.operator,precedence:0,expression:function(a,b){return{evaluate:function(){return a.assign(b.evaluate().value)},assign:f}}},R={tokenType:e.operator,precedence:1,expression:function(a,b){return{evaluate:function(){return g(a.evaluate().value&&b.evaluate().value)},assign:f}}},S={tokenType:e.operator,precedence:1,expression:function(a,b){return{evaluate:function(){return g(a.evaluate().value||b.evaluate().value)},
assign:f}}},T={tokenType:e.operator,precedence:2,expression:function(a,b){return{evaluate:function(){return g(a.evaluate().value==b.evaluate().value)},assign:f}}},U={tokenType:e.operator,precedence:2,expression:function(a,b){return{evaluate:function(){return g(a.evaluate().value!=b.evaluate().value)},assign:f}}},V={tokenType:e.operator,precedence:2,expression:function(a,b){return{evaluate:function(){return g(a.evaluate().value<b.evaluate().value)},assign:f}}},W={tokenType:e.operator,precedence:2,
expression:function(a,b){return{evaluate:function(){return g(a.evaluate().value<=b.evaluate().value)},assign:f}}},X={tokenType:e.operator,precedence:2,expression:function(a,b){return{evaluate:function(){return g(a.evaluate().value>b.evaluate().value)},assign:f}}},Y={tokenType:e.operator,precedence:2,expression:function(a,b){return{evaluate:function(){return g(a.evaluate().value>=b.evaluate().value)},assign:f}}},Z={tokenType:e.operator,precedence:3,expression:function(a,b){return{evaluate:function(){return g(a.evaluate().value+
b.evaluate().value)},assign:f}}},$={tokenType:e.operator,precedence:3,expression:function(a,b){return{evaluate:function(){return g(a.evaluate().value-b.evaluate().value)},assign:f}}},aa={tokenType:e.operator,precedence:4,expression:function(a,b){return{evaluate:function(){return g(a.evaluate().value*b.evaluate().value)},assign:f}}},ba={tokenType:e.operator,precedence:4,expression:function(a,b){return{evaluate:function(){return g(a.evaluate().value/b.evaluate().value)},assign:f}}},ca={tokenType:e.operator,
precedence:4,expression:function(a,b){return{evaluate:function(){return g(a.evaluate().value%b.evaluate().value)},assign:f}}},z=[];z[r.start]={"@":{tokenType:e.array},"(":B,")":v,"-":{tokenType:e.unaryOperator,expression:function(a){return{evaluate:function(){return g(-a.evaluate().value)},assign:f}}},not:{tokenType:e.unaryOperator,expression:function(a){return{evaluate:function(){return g(!a.evaluate().value)},assign:f}}},"true":{tokenType:e.literal,value:!0},"false":{tokenType:e.literal,value:!1},
"null":{tokenType:e.literal,value:null}};z[r.complete]={")":v,",":q,"=":w,equal:T,notEqual:U,lessThan:V,lessThanOrEqual:W,greaterThan:X,greaterThanOrEqual:Y,"+":Z,"-":$,"*":aa,"/":ba,"%":ca,and:R,or:S};z[r.incomplete]=z[r.start];z[r.func]={"(":B};var B={"if":!0,"else":!0,foreach:!0,"in":!0,end:!0,equal:!0,notEqual:!0,lessThan:!0,lessThanOrEqual:!0,greaterThan:!0,greaterThanOrEqual:!0,not:!0,and:!0,or:!0,"true":!0,"false":!0,"null":!0},C={};if(c&&c.length)for(v=0;v<c.length;v++){w=c[v];q=w.name;if(C[q])throw Error(stringFormat("Duplicate function name '{0}'",
[q]));if(!J.test(q)||B[q])throw Error(stringFormat("Illegal function name '{0}'",[q]));C[q]=w.blockFunction?{tokenType:e.blockFunc,operation:w.operation}:{tokenType:e.func,operation:w.operation,propertyResult:w.propertyResult}}var G={};if(b&&b.length)for(v=0;v<b.length;v++)if(w=b[v],q=w.name){if(G[q])throw Error(stringFormat("Duplicate variable name '{0}'",[q]));if(C[q])throw Error(stringFormat("Variable name already used as function name '{0}'",[q]));if(!J.test(q)||B[q])throw Error(stringFormat("Illegal variable name '{0}'",
[q]));G[q]={tokenType:e.variable,value:w.value}}var H={normal:1,array:2},L={bracketType:H.normal},K={bracketType:H.array};this.compile=function(b){function c(a,b){if(z[a][b])return z[a][b];if(a==r.start||a==r.incomplete){if(J.test(b)){if(C[b])return C[b];if(G[b])return G[b]}if(O.test(b))return q[b]||(q[b]={tokenType:e.variable,value:new n}),q[b];if(P.test(b))return{tokenType:e.literal,value:Number(b)};if(Q.test(b))return{tokenType:e.literal,value:b.substring(1,b.length-1).replace(/(\\")/g,'"')}}throw Error(stringFormat("Unexpected token '{0}'",
[b]));}function f(a,b,d){var e=new E,g=r.incomplete;b||(b=0);d||(d=a.length);for(;b<d;b++){var h=c(g,a[b]),g=u[h.tokenType];e.addToken(h)}if(g!=r.complete)throw Error("Unexpected end of statement");return e.getExpression()}function g(a){try{var b=a.match(N);switch(b[0]){case "if":var c=new h(f(b,1));k.addLine(c);m.push(k);k=c;break;case "else":if(k.addCondition)"if"==b[1]?k.addCondition(f(b,2)):k.addCondition(null);else throw Error("Unexpected statement");break;case "foreach":for(c=1;"in"!=b[c];)if(c++,
c==b.length)throw Error("Expected 'in'");var e=f(b,1,c),l=f(b,c+1),F=new p(d,[e,l]);k.addLine(F);m.push(k);k=F;break;case "end":if(1<b.length)throw Error("Unexpected tokens after 'end'");if(0==m.length)throw Error("Unexpected statement");k=m.pop();break;default:var n=f(b);n.block?(k.addLine(n.block),m.push(k),k=n.block):k.addLine(M(n,a))}}catch(I){throw Error(stringFormat("Unable to parse statement '{0}':\n{1}",[a,I.message]));}}var l=new a,m=[],k=l,q={};b=b.match(F);for(var s=0;s<b.length;s++){var t=
b[s];I.test(t)?g(t.substring(1,t.length-1)):k.addLine(A(t.replace(/\[\[/g,"[").replace(/\]\]/g,"]")))}return l}};function PageNumberVariable(b){this.isPageNumber=!0;this.pageId=b}var variables=[],functions=[],sets=[],relations=[];
function StoryTeller(b,c,n,a){function h(a){if(a&&!(a in l.index))throw Error(stringFormat("Page not found: {0}",[pageIdentifier]));return new IntegerVariable(0,l.contents.length-1,D,!1)}function d(a,b){for(var c=!1,d=0;d<b.length;d++)if(null==b[d]){c=!0;break}return{get:function(){return c?a.find.apply(a,b):a.check.apply(a,b)},set:function(d){if(c)throw Error("Relation with null keys cannot be assigned to");d?a.set.apply(a,b):a.clear.apply(a,b);return a.check.apply(a,b)}}}function m(a,b){return{name:a,
operation:function(){return d(b,arguments)},propertyResult:!0}}function p(a,b){return{name:a,operation:function(a,c){return a?c?"number"==typeof a?b.lookupByIndex(a,c):b.lookup(a,c):"number"==typeof a?b.getName(a):b.getIndex(a):b.getAllNames()}}}function f(){var a=l.contents[x.get()];if(a&&a.body)try{var b=E.compile(a.body);g.innerHTML=b.execute()}catch(c){console.log(stringFormat("Error in page '{0}'\n{1}",[a.name,c.message])),g.innerHTML='<span class="error">An error has occurred.</span>'}else console.log(stringFormat("Error. Page number {0} does not exist.",
[x.get()])),g.innerHTML='<span class="error">An error has occurred.</span>';window.scroll(0,0)}for(var g=null,l={contents:[],index:{}},y=document.body.getElementsByTagName("*"),t=0,k=0;k<y.length;k++){var s=y[k];switch(s.className){case "StoryTeller":if(g)throw Error("Multiple 'StoryTeller' Divs");g=s;break;case "page":if(l.index[s.id])throw Error(stringFormat("Duplicate page ID: {0}",[s.id]));l.contents[t]={name:s.id,body:s.innerHTML};l.index[s.id]=t;t++}}g||(g=document.body);var D=0;if(1>l.contents.length)throw Error("No pages found");
l.index.start&&(D=l.index.start);var x=h(),y=[x,random];if(b&&b.length)for(k=0;k<b.length;k++)b[k].isPageNumberVariable&&(b[k]=h(b[k].pageId)),y.push(b[k].value);t=[{name:"randomInteger",operation:random.getInteger.bind(random)},{name:"randomNumber",operation:random.getNumber.bind(random)},{name:"randomBoolean",operation:random.getBoolean.bind(random)},{name:"currentPage",operation:function(){return l.contents[x.get()].name}},{name:"currentPageNumber",operation:function(){return x.get()}},{name:"include",
operation:function(a){if("number"==typeof a)var b=a;else{if(!(a in l.index))throw Error(stringFormat("Page not found: {0}",[a]));b=l.index[a]}try{return E.compile(l.contents[b].body).execute()}catch(c){throw Error(stringFormat("Error in subpage '{0}'\n{1}",[a,c.message]));}}},{name:"link",operation:function(a,b){var c=b.evaluate(),d=A.toBase64();if("number"==typeof c)x.set(c);else{if(!(c in l.index))throw Error(stringFormat("Page not found: {0}",[c]));x.set(l.index[c])}var c=a.execute(),f=new StringBuilder;
f.append('<a href="#');f.append(A.toBase64());f.append('">');f.append(c);f.append("</a>");A.fromBase64(d);return f.getValue()},blockFunction:!0},{name:"reset",operation:function(a){a=a.execute();var b=new StringBuilder;b.append('<a href="#" onclick="window.location.hash = \'\';window.location.reload(true);">');b.append(a);b.append("</a>");return b.getValue()},blockFunction:!0}];if(c&&c.length)for(k=0;k<c.length;k++)t.push(c[k]);if(a&&a.length)for(k=0;k<a.length;k++)c=a[k],y.push(c.relation),t.push(m(c.name,
c.relation));if(n&&n.length)for(k=0;k<n.length;k++)c=n[k],t.push(p(c.name,c.set));var E=new Compiler(b,t),A=new State(y,f);f()}window.onload=function(){new StoryTeller(variables,functions,sets,relations)};
