function StringBuilder(){var b=[];this.append=function(c){null!=c&&b.push(c)};this.getValue=function(){return b.join("")}}function stringFormat(b,c){return b.replace(/{(\d+)}/g,function(b,a){return c[a]})};function BooleanVariable(b){var c=Boolean(b);this.set=function(b){c=Boolean(b)};this.get=function(){return c};this.size=function(){return 1};this.toInt16Array=function(){return c?[1]:[0]};this.fromInt16Array=function(b){c=1==(b[0]&1)}}
function IntegerVariable(b,c,p,a){function k(g){g=Math.floor(g);isNaN(g)&&(g=0);g<b&&(g=a?((g-e)%r+r)%r+b:e);g>c&&(g=a?(g-e)%r+b:m);return g}if(c<b)throw Error("max cannot be less than min");var e=b,m=c,r=c-b+1,g=Math.ceil(Math.log(r)/Math.log(2)),h=k(p);this.set=function(g){h=k(g)};this.get=function(){return h};this.size=function(){return g};this.toInt16Array=function(){for(var a=[],k=Math.ceil(g/16),b=h-e,c=0;c<k;c++)a[c]=b%65536,b=Math.floor(b/65536);return a};this.fromInt16Array=function(g){for(var a=
0,b=g.length-1;0<=b;b--)a*=65536,a+=g[b];h=k(a+e)}}
function NumberVariable(b){function c(a){if(a==Number.POSITIVE_INFINITY)return{sign:0,biasedExponent:2047,mantissa:0};if(a==Number.NEGATIVE_INFINITY)return{sign:1,biasedExponent:2047,mantissa:0};if(isNaN(a))return{sign:1,biasedExponent:2047,mantissa:0xfffffffffffff};if(0==a)return{sign:0,biasedExponent:0,mantissa:0};var k={};k.sign=0>a?1:0;a=Math.abs(a);var e=Math.floor(Math.log(a)/Math.log(2));k.biasedExponent=e+1023;0==k.biasedExponent?(e=Math.pow(2,-1022),k.mantissa=a/e*4503599627370496):(e=Math.pow(2,
e),k.mantissa=4503599627370496*(a/e-1));return k}var p=Number(b);this.set=function(a){p=Number(a)};this.get=function(){return p};this.size=function(){return 64};this.toInt16Array=function(){for(var a=c(p),k=a.mantissa,e=[],b=0;3>b;b++)e[b]=k%65536,k=Math.floor(k/65536);e[3]=a.sign<<15|a.biasedExponent<<4|k;return e};this.fromInt16Array=function(a){var b,e;e=a[3]&15;for(b=2;0<=b;b--)e*=65536,e+=a[b];b=e;e=a[3]>>4&2047;a=a[3]>>15;2047==e?p=0==b?0==a?Number.POSITIVE_INFINITY:Number.NEGATIVE_INFINITY:
NaN:(0==e?(b/=4503599627370496,e=Math.pow(2,-1022)):(b=1+b/4503599627370496,e=Math.pow(2,e-1023)),e*=b,p=1==a?-e:e)}};function Set(){function b(b){var g=a[b];if(g)return g;throw Error(stringFormat("Index not found '{0}'",[b]));}function c(a){if(0<=k[a])return k[a];throw Error(stringFormat("Name not found '{0}'",[a]));}function p(a,g){var h=b(a)[g];if(h)return h;throw Error(stringFormat("Key not found '{0}'",[g]));}for(var a=[],k={},e=0;e<arguments.length;e++){var m=arguments[e];a.push(m);if(!m.name)throw Error("Missing name in set");k[m.name]=e}this.getByIndex=b;this.size=function(){return a.length};this.get=function(a){return b(c(a))};
this.getName=function(a){return b(a).name};this.getAllNames=function(){for(var b=[],g=0;g<a.length;g++)b.push(a[g].name);return b};this.getIndex=c;this.getByIndex=b;this.lookup=function(a,g){return p(c(a),g)};this.lookupByIndex=p}
function Relation(){function b(){if(arguments.length!=k.length)throw Error(stringFormat("Wrong number of keys ({0}), expected ({1})",[arguments.length,k.length]));for(var a=0,b=0;b<k.length;b++)var e=k[b],a=a*e.size()+e.getIndex(arguments[b]);return a}function c(a){a=b.apply(this,a);var h=1<<a%16;return(e[a>>4]&h)==h}function p(a,b,e){for(var m=0;m<a.length&&null!=a[m];)m++;if(m==a.length)c(a)&&e.push(b.slice(0,b.length));else{for(var r=k[m],w=0;w<r.size();w++){var x=r.getName(w);a[m]=x;b.push(x);
p(a,b,e);b.pop()}a[m]=null}}for(var a=1,k=[],e=[],m=0;m<arguments.length;m++){var r=arguments[m],a=a*r.size();k.push(r)}for(m=0;m<a;m+=16)e.push(0);this.set=function(){var a=b.apply(this,arguments),h=a>>4;e[h]|=1<<a%16};this.clear=function(){var a=b.apply(this,arguments),h=a>>4;e[h]&=~(1<<a%16)};this.check=function(){return c(arguments)};this.find=function(){var a=[];p(arguments,[],a);return a};this.size=function(){return a};this.toInt16Array=function(){for(var a=[],b=0;b<e.length;b++)a.push(e[0]);
return a};this.fromInt16Array=function(a){for(var b=0;b<e.length;b++)e[b]=a[b]}};function RandomNumberGenerator(){var b=new IntegerVariable(0,Math.pow(2,32)-1,Math.floor(Math.random()*Math.pow(2,32)),!1),c=Math.pow(2,32),p=Math.pow(2,52);this.getByte=function(){var a=b.get(),a=(1664525*a+1013904223)%c;b.set(a);return(a&1044480)>>12};this.getDouble=function(){for(var a=0,b=0;6>b;b++)a*=256,a+=this.getByte();a=16*a+(this.getByte()>>4);return a/p};this.getBoolean=function(a){return this.getDouble()<a};this.getNumber=function(a,b){return this.getDouble()*(b-a)+a};this.getInteger=
function(a,b){return Math.floor(this.getNumber(a,b))};this.size=function(){return b.size()};this.toInt16Array=function(){return b.toInt16Array()};this.fromInt16Array=function(a){b.fromInt16Array(a)}}var random=new RandomNumberGenerator;var Base64=function(){for(var b={},c=0;64>c;c++)b["0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_".charAt(c)]=c;return{Builder:function(){var b="",a=0,c=0;this.addInt16Array=function(e,m){for(var r=0;r<e.length;r++){for(var g=Math.min(m,16),h=e[r],s=g,h=h<<c|a,s=s+c;6<=s;)b+="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_".charAt(h&63),s-=6,h>>=6;a=h;c=s;m-=g}};this.chars=function(){return 0==c?b:b+"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_".charAt(a)}},
Reader:function(c){function a(a){for(var c=m,p=r;p<a;)c|=b[k.charAt(e++)]<<p,p+=6;r=p-a;m=c>>a;return c&(1<<a)-1}var k=c,e=0,m=0,r=0;this.readInt16Array=function(b){for(var e=[];0<b;){var c=Math.min(b,16);e.push(a(c));b-=c}return e}}}}();function State(b,c){function p(b){b=new Base64.Reader(b);for(var c=0;c<a.length;c++){var k=a[c],g=b.readInt16Array(k.size());k.fromInt16Array(g)}}var a=b;this.toBase64=function(){for(var b=new Base64.Builder,c=0;c<a.length;c++){var k=a[c];b.addInt16Array(k.toInt16Array(),k.size())}return b.chars()};this.fromBase64=p;var k=window.location.hash.replace(/^#/,"");0==k.length?(k=this.toBase64(),window.location.hash=k):p(k);window.setInterval(function(){var a=window.location.hash.replace(/^#/,"");a!=k&&
(k=a,p(k),c())},100)};function Compiler(b,c){function p(){var a;this.get=function(){return a};this.set=function(b){a=b}}function a(){var a=[];this.addLine=function(b){a.push(b)};this.execute=function(){for(var b=new StringBuilder,d=0;d<a.length;d++){var f=a[d];try{b.append(f.execute())}catch(c){if(f.source)throw Error(stringFormat("Unable to execute statement '{0}':\n{1}",[f.source,c.message]));throw c;}}return b.getValue()}}function k(b){function d(b){c={condition:b,block:new a};f.push(c)}var f=[],c;d(b);this.addCondition=
function(a){if(null==c.condition)throw Error("Unreachable 'else' clause");d(a)};this.addLine=function(a){c.block.addLine(a)};this.execute=function(){for(var a=0;a<f.length;a++){var b=f[a];if(null==b.condition||b.condition.evaluate().value)return b.block.execute()}}}function e(a,b,d){d=d.evaluate();for(var f=new StringBuilder,c=0;c<d.length;c++)b.assign(d[c]),f.append(a.execute());return f.getValue()}function m(a){this.evaluate=function(){return a.evaluate().value};this.assign=a.assign.bind(a)}function r(b,
d){for(var f=new a,c=[f],e=0;e<d.length;e++)c.push(new m(d[e]));this.addLine=function(a){f.addLine(a)};this.execute=function(){return b.apply(null,c)}}function g(a){throw Error("Expression cannot be assigned to");}function h(a){return{value:a,output:!0}}function s(a){return{value:a,output:!1}}function l(a){return{evaluate:function(){return h(a)},assign:function(a){throw Error("Attempt to assign to literal");}}}function v(a){return{evaluate:function(){return h(a.get())},assign:function(b){a.set(b);
return s(a.get())}}}function w(a,b,d){return d?{evaluate:function(){evaluatedParameters=b.evaluate().value;return h(a.apply(null,b.items?evaluatedParameters:[evaluatedParameters]).get())},assign:function(d){evaluatedParameters=b.evaluate().value;return s(a.apply(null,b.items?evaluatedParameters:[evaluatedParameters]).set(d))}}:{evaluate:function(){evaluatedParameters=b.evaluate().value;return h(a.apply(null,b.items?evaluatedParameters:[evaluatedParameters]))},assign:g}}function x(a,b){return{block:new r(a,
b.items?b.items:[b]),evaluate:function(){throw Error("Block functions cannot be evaluated in a statement.");},assign:g}}function n(a){return{items:a,evaluate:function(){for(var b=[],d=0;d<a.length;d++)b.push(a[d].evaluate().value);return s(b)},assign:function(b){if(b instanceof Array){for(var d=Math.min(a.length,b.length),f=[],c=0;c<d;c++)f.push(a[c].assign(b[c]));return s(f)}return 0<a.length?s(a[0].assign(b)):s([])}}}function q(){var a=[];this.addToken=function(b){switch(b.tokenType){case d.operator:var f=
a.pop(),c=a.pop();a.push(b.expression(c,f));break;case d.unaryOperator:f=a.pop();a.push(b.expression(f));break;case d.func:a.push(w(b.operation,a.pop(),b.propertyResult));break;case d.blockFunc:a.push(x(b.operation,a.pop()));break;case d.literal:a.push(l(b.value));break;case d.variable:a.push(v(b.value));break;case d.array:a.push(arrayBracket);break;case d.leftBrace:a.push(P);break;case d.leftBracket:a.push(Q);break;case d.functionBracket:a.push(N);break;case d.rightBracket:case d.rightBrace:for(f=
[];!(c=a.pop()).bracketType;)f.push(c);if(b.tokenType==d.rightBrace){if(c.bracketType!=F.curly)throw Error("Mismatched brackets");a.push(n(f.reverse()))}else{if(c.bracketType==F.curly)throw Error("Mismatched brackets");if(c.bracketType==F.func)a.push(n(f.reverse()));else if(1==f.length)a.push(f[0]);else throw Error("Lists must use curly brackets");}}};this.getExpression=function(){if(0==a.length)throw Error("Empty expression");if(1<a.length)throw Error("Incomplete expression");return a.pop()}}function C(){function a(b){if(0==
f.length)return!1;for(var d=f[f.length-1].tokenType,c=0;c<b.length;c++)if(d==b[c])return!0;return!1}function b(a){if(0==f.length)return!1;var c=f[f.length-1];return c.tokenType==d.unaryOperator||c.tokenType==d.operator&&c.precedence>=a}var f=[],c=new q;this.addToken=function(e){switch(e.tokenType){case d.functionBracket:case d.leftBracket:case d.leftBrace:c.addToken(e);f.push(e);break;case d.rightBracket:case d.rightBrace:for(;!a([d.leftBracket,d.leftBrace,d.functionBracket]);)c.addToken(f.pop());
f.pop();c.addToken(e);a([d.func,d.blockFunc])&&c.addToken(f.pop());break;case d.separator:for(;!a([d.leftBracket,d.leftBrace,d.functionBracket]);)c.addToken(f.pop());break;case d.operator:for(;b(e.precedence);)c.addToken(f.pop());f.push(e);break;case d.unaryOperator:f.push(e);break;case d.func:case d.blockFunc:f.push(e);break;default:c.addToken(e)}};this.getExpression=function(){for(;0<f.length;)c.addToken(f.pop());return c.getExpression()}}function A(a){return{execute:function(){return a}}}function H(a,
b){return{execute:function(){var b=a.evaluate();if(b.output)return b.value},source:b}}var O=/((\[\[)|([^[]))+|(\[(("(([\\]")|[^"])*")|([^\]]))*\])/g,L=/^\[(("((\\")|[^"])*")|([^\]]))*\]$/,B=/[^\$_a-zA-Z0-9\s"]|([0-9]*\.[0-9]+)|([0-9]+)|(\$[_a-zA-Z0-9]+)|([_a-zA-Z][_a-zA-Z0-9]*)|("((\\")|[^"])*")/g,G=/^[_a-zA-Z][_a-zA-Z0-9]*$/,I=/^\$[_a-zA-Z0-9]+$/,f=/^([0-9]*\.[0-9])|([0-9]+)$/,D=/^"((\\")|[^"])*"$/,d={functionBracket:1,leftBracket:2,rightBracket:3,leftBrace:4,rightBrace:5,separator:6,func:7,blockFunc:8,
operator:9,unaryOperator:10,variable:11,literal:12,marker:13},u=[];u[d.leftBracket]=1;u[d.functionBracket]=1;u[d.rightBracket]=3;u[d.leftBrace]=1;u[d.rightBrace]=3;u[d.separator]=1;u[d.func]=4;u[d.blockFunc]=4;u[d.operator]=2;u[d.unaryOperator]=2;u[d.variable]=3;u[d.literal]=3;var N={tokenType:d.functionBracket},J={tokenType:d.rightBracket},y={tokenType:d.rightBrace},t={tokenType:d.separator},z={tokenType:d.operator,precedence:0,expression:function(a,b){return{evaluate:function(){return a.assign(b.evaluate().value)},
assign:g}}},R={tokenType:d.operator,precedence:1,expression:function(a,b){return{evaluate:function(){return h(a.evaluate().value&&b.evaluate().value)},assign:g}}},S={tokenType:d.operator,precedence:1,expression:function(a,b){return{evaluate:function(){return h(a.evaluate().value||b.evaluate().value)},assign:g}}},T={tokenType:d.operator,precedence:2,expression:function(a,b){return{evaluate:function(){return h(a.evaluate().value==b.evaluate().value)},assign:g}}},U={tokenType:d.operator,precedence:2,
expression:function(a,b){return{evaluate:function(){return h(a.evaluate().value!=b.evaluate().value)},assign:g}}},V={tokenType:d.operator,precedence:2,expression:function(a,b){return{evaluate:function(){return h(a.evaluate().value<b.evaluate().value)},assign:g}}},W={tokenType:d.operator,precedence:2,expression:function(a,b){return{evaluate:function(){return h(a.evaluate().value<=b.evaluate().value)},assign:g}}},X={tokenType:d.operator,precedence:2,expression:function(a,b){return{evaluate:function(){return h(a.evaluate().value>
b.evaluate().value)},assign:g}}},Y={tokenType:d.operator,precedence:2,expression:function(a,b){return{evaluate:function(){return h(a.evaluate().value>=b.evaluate().value)},assign:g}}},Z={tokenType:d.operator,precedence:3,expression:function(a,b){return{evaluate:function(){var f=a.evaluate().value,d=b.evaluate().value;return f instanceof Array?d instanceof Array?h(f.concat(d)):h(f.concat([d])):d instanceof Array?h([f].concat(d)):h(f+d)},assign:g}}},$={tokenType:d.operator,precedence:3,expression:function(a,
b){return{evaluate:function(){return h(a.evaluate().value-b.evaluate().value)},assign:g}}},aa={tokenType:d.operator,precedence:4,expression:function(a,b){return{evaluate:function(){return h(a.evaluate().value*b.evaluate().value)},assign:g}}},ba={tokenType:d.operator,precedence:4,expression:function(a,b){return{evaluate:function(){return h(a.evaluate().value/b.evaluate().value)},assign:g}}},ca={tokenType:d.operator,precedence:4,expression:function(a,b){return{evaluate:function(){return h(a.evaluate().value%
b.evaluate().value)},assign:g}}},da={tokenType:d.operator,precedence:5,expression:function(a,b){return{evaluate:function(){var f;f=a.evaluate().value;f=f instanceof Array?f:[f];var d=b.evaluate().value;if(d instanceof Array){for(var c=[],e=0;e<d.length;e++){var g=d[e];0>g&&(g=f.length+g);0<=g&&g<f.length?c.push(f[g]):c.push(null)}return h(c)}0>d&&(d=f.length+d);return 0<=d&&d<f.length?h(f[d]):h(null)},assign:g}}},E=[];E[1]={"(":{tokenType:d.leftBracket},")":J,"{":{tokenType:d.leftBrace},"}":y,"-":{tokenType:d.unaryOperator,
expression:function(a){return{evaluate:function(){return h(-a.evaluate().value)},assign:g}}},not:{tokenType:d.unaryOperator,expression:function(a){return{evaluate:function(){return h(!a.evaluate().value)},assign:g}}},"true":{tokenType:d.literal,value:!0},"false":{tokenType:d.literal,value:!1},"null":{tokenType:d.literal,value:null}};E[3]={")":J,"}":y,",":t,"=":z,equal:T,notEqual:U,lessThan:V,lessThanOrEqual:W,greaterThan:X,greaterThanOrEqual:Y,"+":Z,"-":$,"*":aa,"/":ba,"%":ca,and:R,or:S,"@":da};E[2]=
E[1];E[4]={"(":N};var J={"if":!0,"else":!0,foreach:!0,"in":!0,end:!0,equal:!0,notEqual:!0,lessThan:!0,lessThanOrEqual:!0,greaterThan:!0,greaterThanOrEqual:!0,not:!0,and:!0,or:!0,"true":!0,"false":!0,"null":!0},K={};if(c&&c.length)for(y=0;y<c.length;y++){z=c[y];t=z.name;if(K[t])throw Error(stringFormat("Duplicate function name '{0}'",[t]));if(!G.test(t)||J[t])throw Error(stringFormat("Illegal function name '{0}'",[t]));K[t]=z.blockFunction?{tokenType:d.blockFunc,operation:z.operation}:{tokenType:d.func,
operation:z.operation,propertyResult:z.propertyResult}}var M={};if(b&&b.length)for(y=0;y<b.length;y++)if(z=b[y],t=z.name){if(M[t])throw Error(stringFormat("Duplicate variable name '{0}'",[t]));if(K[t])throw Error(stringFormat("Variable name already used as function name '{0}'",[t]));if(!G.test(t)||J[t])throw Error(stringFormat("Illegal variable name '{0}'",[t]));M[t]={tokenType:d.variable,value:z.value}}var F={normal:1,func:2,curly:3},Q={bracketType:F.normal},N={bracketType:F.func},P={bracketType:F.curly};
this.compile=function(b){function c(a,b){if(E[a][b])return E[a][b];if(1==a||2==a){if(G.test(b)){if(K[b])return K[b];if(M[b])return M[b]}if(I.test(b))return q[b]||(q[b]={tokenType:d.variable,value:new p}),q[b];if(f.test(b))return{tokenType:d.literal,value:Number(b)};if(D.test(b))return{tokenType:d.literal,value:b.substring(1,b.length-1).replace(/(\\")/g,'"')}}throw Error(stringFormat("Unexpected token '{0}'",[b]));}function g(a,b,f){var d=new C,e=2;b||(b=0);f||(f=a.length);for(;b<f;b++){var D=c(e,
a[b]),e=u[D.tokenType];d.addToken(D)}if(3!=e)throw Error("Unexpected end of statement");return d.getExpression()}function h(a){try{var b=a.match(B);switch(b[0]){case "if":var f=new k(g(b,1));l.addLine(f);n.push(l);l=f;break;case "else":if(l.addCondition)"if"==b[1]?l.addCondition(g(b,2)):l.addCondition(null);else throw Error("Unexpected statement");break;case "foreach":for(f=1;"in"!=b[f];)if(f++,f==b.length)throw Error("Expected 'in'");var d=g(b,1,f),c=g(b,f+1),D=new r(e,[d,c]);l.addLine(D);n.push(l);
l=D;break;case "end":if(1<b.length)throw Error("Unexpected tokens after 'end'");if(0==n.length)throw Error("Unexpected statement");l=n.pop();break;default:var u=g(b);u.block?(l.addLine(u.block),n.push(l),l=u.block):l.addLine(H(u,a))}}catch(m){throw Error(stringFormat("Unable to parse statement '{0}':\n{1}",[a,m.message]));}}var m=new a,n=[],l=m,q={};b=b.match(O);for(var t=0;t<b.length;t++){var s=b[t];L.test(s)?h(s.substring(1,s.length-1)):l.addLine(A(s.replace(/\[\[/g,"[").replace(/\]\]/g,"]")))}return m}}
;function PageNumberVariable(b){this.isPageNumber=!0;this.pageId=b}var variables=[],functions=[],sets=[],relations=[];
function StoryTeller(b,c,p,a){function k(a){if(a){if(!(a in l.index))throw Error(stringFormat("Page not found: {0}",[a]));a=l.index[a]}else a=L;return new IntegerVariable(0,l.contents.length-1,a,!1)}function e(a){if(!(a in l.index))throw Error(stringFormat("Page not found: {0}",[a]));var b=l.index[a];return{get:function(){return b},set:function(){throw Error("Cannot update page of a static viewport.");}}}function m(a,b){for(var d=!1,c=0;c<b.length;c++)if(null==b[c]){d=!0;break}return{get:function(){return d?
a.find.apply(a,b):a.check.apply(a,b)},set:function(c){if(d)throw Error("Relation with null keys cannot be assigned to");c?a.set.apply(a,b):a.clear.apply(a,b);return a.check.apply(a,b)}}}function r(a,b){return{name:a,operation:function(){return m(b,arguments)},propertyResult:!0}}function g(a,b){return{name:a,operation:function(a,f){return a?f?"number"==typeof a?b.lookupByIndex(a,f):b.lookup(a,f):"number"==typeof a?b.getName(a):b.getIndex(a):b.getAllNames()}}}function h(a,b){var d=l.contents[b.get()];
if(d&&d.body)try{var c=G.compile(d.body);a.innerHTML=c.execute()}catch(e){console.log(stringFormat("Error in page '{0}'\n{1}",[d.name,e.message])),a.innerHTML='<span class="error">An error has occurred.</span>'}else console.log(stringFormat("Error. Page number {0} does not exist.",[B.get()])),a.innerHTML='<span class="error">An error has occurred.</span>'}function s(){h(x,B);for(var a=0;a<v.contents.length;a++){var b=v.contents[a];h(b.element,b.pageId)}window.scroll(0,0)}for(var l={contents:[],index:{}},
v={contents:[],index:{}},w=document.body.getElementsByTagName("div"),x=null,n=0;n<w.length;n++){var q=w[n],C=q.getAttribute("data-page-id"),A=q.getAttribute("data-viewport-id"),H=q.getAttribute("data-viewport-page"),O=q.getAttribute("data-viewport-type");if(C){if(l.index[C])throw Error(stringFormat("Duplicate page ID: {0}",[C]));l.index[C]=l.contents.length;l.contents.push({name:C,body:q.innerHTML})}if(A)if("main"==A){if(x)throw Error(stringFormat("Duplicate main viewport."));if(H)throw Error("Main viewport cannot have a default page.");
x=q}else{if(v.index[A])throw Error(stringFormat("Duplicate viewport ID: {0}",[A]));if(!H)throw Error(stringFormat("Viewport '{0}' does not have a default page.",[A]));v.index[A]=v.contents.length;v.contents.push({name:A,element:q,defaultPage:H,dynamic:"dynamic"==O})}}if(!x){if(0<v.length)throw Error("Main viewport must be specified if any other viewports are.");x=document.body}var L=0;if(1>l.contents.length)throw Error("No pages found");l.index.start&&(L=l.index.start);for(var B=k(),w=[random,B],
n=0;n<v.contents.length;n++)q=v.contents[n],q.dynamic?(q.pageId=k(q.defaultPage),w.push(q.pageId)):q.pageId=e(q.defaultPage);if(b&&b.length)for(n=0;n<b.length;n++)b[n].isPageNumberVariable&&(b[n]=k(b[n].pageId)),w.push(b[n].value);q=[{name:"randomInteger",operation:random.getInteger.bind(random)},{name:"randomNumber",operation:random.getNumber.bind(random)},{name:"randomBoolean",operation:random.getBoolean.bind(random)},{name:"currentPage",operation:function(){return l.contents[B.get()].name}},{name:"currentPageNumber",
operation:function(){return B.get()}},{name:"include",operation:function(a){if("number"==typeof a)var b=a;else{if(!(a in l.index))throw Error(stringFormat("Page not found: {0}",[a]));b=l.index[a]}try{return G.compile(l.contents[b].body).execute()}catch(d){throw Error(stringFormat("Error in subpage '{0}'\n{1}",[a,d.message]));}}},{name:"length",operation:function(a){return a.length}},{name:"none",operation:function(a){return 0==a.length}},{name:"any",operation:function(a){return 0<a.length}},{name:"first",
operation:function(a){return 0<a.length?a[0]:null}},{name:"concat",operation:function(a,b){a instanceof Array||(a=[a]);b instanceof Array||(b=[b]);return a.concat(b)}},{name:"exceptFirst",operation:function(a){return a.slice(1)}},{name:"last",operation:function(a){return 0<a.length?a[a.length-1]:null}},{name:"exceptLast",operation:function(a){return a.slice(0,a.length-1)}},{name:"peel",operation:function(a){return 1<a.length?[a[0],a.slice(1,a.length-1),a[a.length-1]]:0<a.length?[a[0],[],null]:[null,
[],null]}},{name:"peelFirst",operation:function(a){return 0<a.length?[a[0],a.slice(1,a.length)]:[null,[]]}},{name:"peelLast",operation:function(a){return 0<a.length?[a.slice(0,a.length-1),a[a.length-1]]:[[],null]}},{name:"index",operation:function(a){for(var b=[],d=a.length,c=0;c<d;c++)b.push([a[c],c,c-d]);return b}},{name:"mark",operation:function(a){var b=[],d=a.length-1;b.push([a[0],!0,!1]);for(var c=1;c<d;c++)b.push([a[c],!1,!1]);b.push([a[d],!1,!0]);return b}},{name:"viewport",operation:function(a,
b){if(!(a in v.index))throw Error(stringFormat("Viewport does not exist: {0}",[a]));var d=v.contents[v.index[a]];if(b)if("number"==typeof b)d.pageId.set(b);else{if(!(b in l.index))throw Error(stringFormat("Page not found: {0}",[b]));d.pageId.set(l.index[b])}else return d.pageId.get()}},{name:"link",operation:function(a,b){var d=I.toBase64();if(b){var c=b.evaluate();if("number"==typeof c)B.set(c);else{if(!(c in l.index))throw Error(stringFormat("Page not found: {0}",[c]));B.set(l.index[c])}}var c=
a.execute(),e=new StringBuilder;e.append('<a href="#');e.append(I.toBase64());e.append('">');e.append(c);e.append("</a>");I.fromBase64(d);return e.getValue()},blockFunction:!0},{name:"reset",operation:function(a){a=a.execute();var b=new StringBuilder;b.append('<a href="#" onclick="window.location.hash = \'\';window.location.reload(true);">');b.append(a);b.append("</a>");return b.getValue()},blockFunction:!0}];if(c&&c.length)for(n=0;n<c.length;n++)q.push(c[n]);if(a&&a.length)for(n=0;n<a.length;n++)c=
a[n],w.push(c.relation),q.push(r(c.name,c.relation));if(p&&p.length)for(n=0;n<p.length;n++)c=p[n],q.push(g(c.name,c.set));var G=new Compiler(b,q),I=new State(w,s);s()}window.onload=function(){new StoryTeller(variables,functions,sets,relations)};
